name: Build & Test PR

on:
  pull_request:
    branches: [ master ]

env:
  NETCORE_VERSION: '7.0.x'

jobs:
  build:
    name: Build and test
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core LTS
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setting up .NET Core SDK ${{ env.NETCORE_VERSION }}...
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore Workloads
        run: dotnet workload restore

      - name: Restoring Packages
        run: dotnet restore

      - name: Building Solution
        run: dotnet build TabloRazor.sln --configuration Release --no-restore 
        
      - name: Testing
        run: dotnet test --no-build --configuration Release --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"
      
      - name: Testing coverage result copy
        run: copy .\TabloRazor.Tests\coverage.net7.0.opencover.xml .\opencover.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
