name: 'Publish to Github pages'
on:
  push:
    branches:
      - master
env:
  PUBLISH_DIR: docs/Tabler.Docs.Wasm/bin/Release/net6.0/publish/wwwroot

jobs:
  build:
    runs-on: windows-2022
    steps:
        # Checkout the code
        - uses: actions/checkout@v2
        
        - name: Setup .NET Core LTS
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.0.x
      
        - name: Restore Workloads
          run: dotnet workload restore
      
        - name: Test
          run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"
        
        - name: Testing coverage result copy
          run: copy .\TabloRazor.Tests\coverage.net7.0.opencover.xml .\opencover.xml
          
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            
        - name: Publish
          run: dotnet publish Tabler.Docs.Wasm.csproj --configuration Release --framework net7.0
          working-directory: ./docs/Tabler.Docs.Wasm
    
        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: docs/Tabler.Docs.Wasm/bin/Release/net7.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
