on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

        # Install .NET Core SDK
    - name: Setup .NET Core LTS 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET Core 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Setup .NET Core LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Dotnet Pack 
      working-directory: src/TabloRazor
      run: dotnet pack -c Release -p:Version=${GITHUB_REF##*/v}

    - name: Dotnet Nuget Push   
      working-directory: src/TabloRazor/bin/Release
      run: dotnet nuget push TabloRazor.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      continue-on-error: true
      
    - name: Dotnet Pack 
      working-directory: src/TabloRazor.QuickTable.EntityFramework
      run: dotnet pack -c Release -p:Version=${GITHUB_REF##*/v}

    - name: Dotnet Nuget Push   
      working-directory: src/TabloRazor.QuickTable.EntityFramework/bin/Release
      run: dotnet nuget push TabloRazor.QuickTable.EntityFramework.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      continue-on-error: true
      
    - name: Dotnet Pack 
      working-directory: src/TabloRazor.Assets
      run: dotnet pack -c Release -p:Version=${GITHUB_REF##*/v}

    - name: Dotnet Nuget Push   
      working-directory: src/TabloRazor.Assets/bin/Release
      run: dotnet nuget push TabloRazor.Assets.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      continue-on-error: true